name: Update README.md and publish release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Python script to update README.md
        run: python .github/workflows/update.py

      - name: Set Git Config
        run: |
          git config --global user.name "Skyler Sun"
          git config --global user.email "3385213313@qq.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Commit message"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
