name: Update README.md and publish release

on:
  push:
    main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'

      - name: Run Python script
        run: python update.py